import { NextRequest, NextResponse } from "next/server";

export async function GET(
  req: NextRequest,
  context: { params: Promise<{ assetId: string }> }
) {
  const { assetId } = await context.params;
  const origin = process.env.NEXT_PUBLIC_SITE_URL || new URL(req.url).origin;

  const cid = "QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco";

  return NextResponse.json({
    name: "ChainTrust Audit Badge",
    unit_name: "AUDITNFT",
    description: "Proof-of-Audit Non-Fungible Token generated by ChainTrust AI Due Diligence Engine",
    image: `ipfs://${cid}/audit-badge.png`,
    image_url: `https://ipfs.algonode.xyz/ipfs/${cid}/audit-badge.png`,
    image_url_backup: `https://ipfs.algonode.dev/ipfs/${cid}/audit-badge.png`,
    external_url: `${origin}/nft-badge`,
    properties: {
      standard: "ARC-0003",
      asset_id: Number(assetId || 789410293),
      total_supply: 1,
      decimals: 0,
      report_id: "ANL-58440",
      sha256_hash: "b3b1b1ab12e4a7d5362110b2b8580283c3d5b58a4d8b64244b7be58f1a2ab24e",
      confirmed_round: 48291231,
      network: "Algorand TestNet",
      ipfs_gateway: "https://ipfs.algonode.xyz/ipfs/",
      ipfs_gateway_backup: "https://ipfs.algonode.dev/ipfs/"
    }
  });
}
